const PDFDocument = require('pdfkit');
const createCSVStringifier = require('csv-writer').createObjectCsvStringifier;
const fs = require('fs');
const path = require('path');
const moment = require('moment-timezone');

// Export controller for handling PDF and CSV exports
class ExportController {
  // Generate metadata block for exports
  static generateMetadata(req, widgetName, source) {
    const user = req.user || { firstName: 'System', lastName: 'User', email: 'system@university.edu' };
    const timezone = 'Asia/Manila';
    const timestamp = moment().tz(timezone);
    
    // Extract active filters from query params
    const filters = {};
    const { year, month, startDate, endDate, status, department, search, sort } = req.query;
    
    if (year && year !== 'all') filters.year = year;
    if (month && month !== 'all') filters.month = month;
    if (startDate) filters.startDate = startDate;
    if (endDate) filters.endDate = endDate;
    if (status && status !== 'all') filters.status = status;
    if (department && department !== 'all') filters.department = department;
    if (search) filters.search = search;
    if (sort) filters.sort = sort;

    return {
      exportedBy: `${user.firstName} ${user.lastName} (${user.email})`,
      exportDate: timestamp.format('YYYY-MM-DD HH:mm:ss z'),
      exportDateISO: timestamp.toISOString(),
      source: source,
      widget: widgetName,
      filters: Object.keys(filters).length > 0 ? filters : { note: 'No filters applied' },
      timezone: timezone
    };
  }

  // Generate filename with timestamp
  static generateFilename(module, widgetName, format) {
    const timestamp = moment().tz('Asia/Manila').format('YYYYMMDD-HHmm');
    // Clean widget name for filename
    const cleanWidgetName = widgetName.replace(/[^a-zA-Z0-9]/g, '');
    return `${module}_${cleanWidgetName}_${timestamp}.${format}`;
  }

  // Export table data to CSV
  static async exportTableToCSV(data, columns, metadata, filename) {
    try {
      // Create CSV header with metadata
      let csvContent = `# Export Metadata\n`;
      csvContent += `# Generated by: ${metadata.exportedBy}\n`;
      csvContent += `# Export Date: ${metadata.exportDate}\n`;
      csvContent += `# Source: ${metadata.source}\n`;
      csvContent += `# Widget: ${metadata.widget}\n`;
      csvContent += `# Active Filters: ${JSON.stringify(metadata.filters)}\n`;
      csvContent += `# Total Records: ${data.length}\n`;
      csvContent += `#\n\n`;

      // Create CSV stringifier
      const csvStringifier = createCSVStringifier({
        header: columns.map(col => ({ id: col.key, title: col.title }))
      });

      // Add headers and data
      csvContent += csvStringifier.getHeaderString();
      csvContent += csvStringifier.stringifyRecords(data);

      return {
        content: csvContent,
        filename: filename,
        mimeType: 'text/csv'
      };
    } catch (error) {
      throw new Error(`CSV export failed: ${error.message}`);
    }
  }

  // Export table data to PDF
  static async exportTableToPDF(data, columns, metadata, filename, title) {
    try {
      return new Promise((resolve, reject) => {
        const doc = new PDFDocument({ margin: 40, size: 'A4' });
        let buffers = [];
        
        doc.on('data', buffers.push.bind(buffers));
        doc.on('end', () => {
          const pdfData = Buffer.concat(buffers);
          resolve({
            content: pdfData,
            filename: filename,
            mimeType: 'application/pdf'
          });
        });

        // Add title
        doc.fontSize(16).font('Helvetica-Bold').text(title, { align: 'center' });
        doc.moveDown();

        // Add metadata block
        doc.fontSize(10).font('Helvetica');
        doc.text(`Generated by: ${metadata.exportedBy}`, 40, doc.y);
        doc.text(`Export Date: ${metadata.exportDate}`, 40, doc.y);
        doc.text(`Source: ${metadata.source}`, 40, doc.y);
        doc.text(`Total Records: ${data.length}`, 40, doc.y);
        doc.text(`Active Filters: ${JSON.stringify(metadata.filters)}`, 40, doc.y, { width: 500 });
        doc.moveDown();

        // Calculate column widths
        const pageWidth = doc.page.width - 80; // Account for margins
        const colWidth = pageWidth / columns.length;

        // Add table headers
        let yPos = doc.y;
        doc.fontSize(9).font('Helvetica-Bold');
        columns.forEach((col, index) => {
          doc.text(col.title, 40 + (index * colWidth), yPos, { width: colWidth - 5, align: 'left' });
        });
        
        // Add header line
        yPos += 15;
        doc.moveTo(40, yPos).lineTo(doc.page.width - 40, yPos).stroke();
        yPos += 5;

        // Add table data
        doc.font('Helvetica');
        data.forEach((row, rowIndex) => {
          // Check if we need a new page
          if (yPos > doc.page.height - 100) {
            doc.addPage();
            yPos = 40;
          }

          columns.forEach((col, colIndex) => {
            const cellValue = this.formatCellValue(row[col.key]);
            doc.text(cellValue, 40 + (colIndex * colWidth), yPos, { 
              width: colWidth - 5, 
              align: 'left',
              height: 12
            });
          });
          yPos += 15;
        });

        doc.end();
      });
    } catch (error) {
      throw new Error(`PDF export failed: ${error.message}`);
    }
  }

  // Export chart data to PDF
  static async exportChartToPDF(chartData, metadata, filename, title, chartType = 'table') {
    try {
      return new Promise((resolve, reject) => {
        const doc = new PDFDocument({ margin: 40, size: 'A4' });
        let buffers = [];
        
        doc.on('data', buffers.push.bind(buffers));
        doc.on('end', () => {
          const pdfData = Buffer.concat(buffers);
          resolve({
            content: pdfData,
            filename: filename,
            mimeType: 'application/pdf'
          });
        });

        // Add title
        doc.fontSize(16).font('Helvetica-Bold').text(title, { align: 'center' });
        doc.moveDown();

        // Add metadata block
        doc.fontSize(10).font('Helvetica');
        doc.text(`Generated by: ${metadata.exportedBy}`, 40, doc.y);
        doc.text(`Export Date: ${metadata.exportDate}`, 40, doc.y);
        doc.text(`Source: ${metadata.source}`, 40, doc.y);
        doc.text(`Chart Type: ${chartType}`, 40, doc.y);
        doc.text(`Active Filters: ${JSON.stringify(metadata.filters)}`, 40, doc.y, { width: 500 });
        doc.moveDown();

        // Convert chart data to table format
        if (Array.isArray(chartData)) {
          // Simple data array (like pie chart)
          doc.fontSize(12).font('Helvetica-Bold').text('Chart Data:');
          doc.moveDown(0.5);
          
          doc.fontSize(10).font('Helvetica');
          chartData.forEach(item => {
            if (typeof item === 'object') {
              const label = item.name || item.label || item._id || 'Item';
              const value = item.value || item.count || item.y || '0';
              const percentage = item.percentage ? ` (${item.percentage}%)` : '';
              doc.text(`• ${label}: ${value}${percentage}`);
            } else {
              doc.text(`• ${item}`);
            }
          });
        } else if (typeof chartData === 'object') {
          // Complex chart data object
          Object.keys(chartData).forEach(key => {
            doc.fontSize(10).font('Helvetica-Bold').text(`${key}:`);
            if (Array.isArray(chartData[key])) {
              chartData[key].forEach(item => {
                if (typeof item === 'object') {
                  doc.font('Helvetica').text(`  • ${JSON.stringify(item)}`);
                } else {
                  doc.font('Helvetica').text(`  • ${item}`);
                }
              });
            } else {
              doc.font('Helvetica').text(`  ${chartData[key]}`);
            }
            doc.moveDown(0.5);
          });
        }

        doc.end();
      });
    } catch (error) {
      throw new Error(`Chart PDF export failed: ${error.message}`);
    }
  }

  // Export chart data to CSV
  static async exportChartToCSV(chartData, metadata, filename) {
    try {
      // Create CSV header with metadata
      let csvContent = `# Export Metadata\n`;
      csvContent += `# Generated by: ${metadata.exportedBy}\n`;
      csvContent += `# Export Date: ${metadata.exportDate}\n`;
      csvContent += `# Source: ${metadata.source}\n`;
      csvContent += `# Widget: ${metadata.widget}\n`;
      csvContent += `# Active Filters: ${JSON.stringify(metadata.filters)}\n`;
      csvContent += `#\n\n`;

      // Convert chart data to CSV format
      if (Array.isArray(chartData)) {
        // Determine CSV structure based on data
        const firstItem = chartData[0];
        if (typeof firstItem === 'object') {
          const keys = Object.keys(firstItem);
          csvContent += keys.join(',') + '\n';
          chartData.forEach(item => {
            const values = keys.map(key => {
              const value = item[key];
              // Escape CSV values
              return typeof value === 'string' && value.includes(',') 
                ? `"${value.replace(/"/g, '""')}"` 
                : value;
            });
            csvContent += values.join(',') + '\n';
          });
        } else {
          csvContent += 'Value\n';
          chartData.forEach(item => {
            csvContent += `"${item}"\n`;
          });
        }
      } else if (typeof chartData === 'object') {
        csvContent += 'Category,Value\n';
        Object.keys(chartData).forEach(key => {
          csvContent += `"${key}","${chartData[key]}"\n`;
        });
      }

      return {
        content: csvContent,
        filename: filename,
        mimeType: 'text/csv'
      };
    } catch (error) {
      throw new Error(`Chart CSV export failed: ${error.message}`);
    }
  }

  // Format cell values for display
  static formatCellValue(value) {
    if (value === null || value === undefined) return '';
    if (typeof value === 'object') {
      if (value instanceof Date) {
        return moment(value).tz('Asia/Manila').format('YYYY-MM-DD HH:mm');
      }
      return JSON.stringify(value);
    }
    return String(value).substring(0, 100); // Limit cell length
  }

  // Log export action for audit
  static async logExportAction(req, module, widget, format, rowCount) {
    try {
      const user = req.user || { _id: 'system', email: 'system@university.edu' };
      const logEntry = {
        userId: user._id,
        userEmail: user.email,
        action: 'EXPORT',
        module: module,
        widget: widget,
        format: format.toUpperCase(),
        rowCount: rowCount,
        filters: req.query,
        timestamp: new Date(),
        ipAddress: req.ip || req.connection.remoteAddress
      };

      // In a real implementation, save this to an audit log collection
      console.log('EXPORT AUDIT:', JSON.stringify(logEntry, null, 2));
      
      // TODO: Save to database audit log table
      // await AuditLog.create(logEntry);
      
    } catch (error) {
      console.error('Failed to log export action:', error);
      // Don't fail the export if logging fails
    }
  }
}

module.exports = ExportController;
